# Generated by Django 5.1.5 on 2025-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('funciones', models.TextField()),
                ('horario', models.CharField(max_length=500)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
            ],
        ),
    ]
